name: ACS_CICD

on:
  push:
     branches: [ aks ]
jobs:
  docker-build-and-deploy:
    runs-on: ubuntu:latest 
    
    steps:
       - name: checkout
         uses: actions/checkout@v5.0.0
       - name: Build Docker Image and Push to Docker Hub
         uses: GlueOps/github-actions-build-push-containers@v0.4.1
         with:
            registry: docker.io
            image_name: sourabhtailor/acr
            dockerhub_username: sourabhtailor
            dockerhub_password: dckr_pat_8TqYvBbmviq5kLCArR21qaxVftI
